- task: GithubRelease@0
  displayName: 'Create GitHub Release'
  inputs:
    gitHubConnection: Analyse4
    repositoryName: Analyse4/digimon-cli
    isPreRelease: true
    assets: $(Build.ArtifactStagingDirectory)/*
