trigger:
  - master
#variables:
#  GOPATH: 'C:\\usr\\gopath'
#  GOBIN:  '$(GOPATH)/bin' # Go binaries path
#  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

stages:

  - stage: Build
    jobs:

      - job: Build
        pool:
          vmImage: windows-latest
        steps:
          - bash: |
              echo "##vso[task.setvariable variable=gopath]C:\\usr\\gopath"
          - bash: |
              echo "##vso[task.setvariable variable=gobin]$(GOPATH)/bin"
          - bash: |
              echo "##vso[task.setvariable variable=modulepath]$(GOPATH)/src/github.com/$(build.repository.name)"
          - bash: |
              mkdir -p $(GOBIN)
              mkdir -p $(GOPATH)/pkg
              mkdir -p $(MODULEPATH)
              shopt -s extglob
              shopt -s dotglob
              mv * $(MODULEPATH)
              echo '##vso[task.prependpath]$(GOBIN)'
              echo '##vso[task.prependpath]$(GOROOT)/bin'

              echo $(GOPATH)
              ls $(GOPATH)
            displayName: 'Set up the Go workspace'
          - bash: |
              cd $(MODULEPATH)
              go version
              go get -v -t -d ./...
              if [ -f Gopkg.toml ]; then
                  curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
                  dep ensure
              fi
              go install -v
            displayName: 'Get dependencies, then build'
#          - script: |
#              set %system.defaultWorkingDirectory%
#              move %GOBIN%/digimon-cli %system.defaultWorkingDirectory%
          - publish: $(GOBIN)
            artifact: LinuxBinary

#          - bash: |
#              go version
#              go get -v -t -d ./...
#              if [ -f Gopkg.toml ]; then
#                  curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#                  dep ensure
#              fi
#              go install -v
#            workingDirectory: '$(modulePath)'
#          - bash: |
#              echo $(GOPATH)
#              echo $(GOBIN)
#              ls $(GOBIN)
#            displayName: 'testenv'
#            workingDirectory: '$(modulePath)'
#          - publish: $(GOBIN)/*
#            artifact: WindowsBinary